package com.bafar.buro.ws.hibernate;
// Generated 07-ago-2016 21:11:12 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * SgfensProspectoDatosCredito generated by hbm2java
 */
public class SgfensProspectoDatosCredito  implements java.io.Serializable {


     private int idProspectoDatosCredito;
     private int idSgfensProspecto;
     private String direccion;
     private String coloniaPoblacion;
     private String delegacionMunicipio;
     private String ciudad;
     private String estado;
     private String codigoPostal;
     private String nombreScore;
     private String codigoScore;
     private String valorScore;
     private String cuentas;
     private Date fechaConsulta;

    public SgfensProspectoDatosCredito() {
    }

	
    public SgfensProspectoDatosCredito(int idProspectoDatosCredito, int idSgfensProspecto) {
        this.idProspectoDatosCredito = idProspectoDatosCredito;
        this.idSgfensProspecto = idSgfensProspecto;
    }
    public SgfensProspectoDatosCredito(int idProspectoDatosCredito, int idSgfensProspecto, String direccion, String coloniaPoblacion, String delegacionMunicipio, String ciudad, String estado, String codigoPostal, String nombreScore, String codigoScore, String valorScore, String cuentas, Date fechaConsulta) {
       this.idProspectoDatosCredito = idProspectoDatosCredito;
       this.idSgfensProspecto = idSgfensProspecto;
       this.direccion = direccion;
       this.coloniaPoblacion = coloniaPoblacion;
       this.delegacionMunicipio = delegacionMunicipio;
       this.ciudad = ciudad;
       this.estado = estado;
       this.codigoPostal = codigoPostal;
       this.nombreScore = nombreScore;
       this.codigoScore = codigoScore;
       this.valorScore = valorScore;
       this.cuentas = cuentas;
       this.fechaConsulta = fechaConsulta;
    }
   
    public int getIdProspectoDatosCredito() {
        return this.idProspectoDatosCredito;
    }
    
    public void setIdProspectoDatosCredito(int idProspectoDatosCredito) {
        this.idProspectoDatosCredito = idProspectoDatosCredito;
    }
    public int getIdSgfensProspecto() {
        return this.idSgfensProspecto;
    }
    
    public void setIdSgfensProspecto(int idSgfensProspecto) {
        this.idSgfensProspecto = idSgfensProspecto;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getColoniaPoblacion() {
        return this.coloniaPoblacion;
    }
    
    public void setColoniaPoblacion(String coloniaPoblacion) {
        this.coloniaPoblacion = coloniaPoblacion;
    }
    public String getDelegacionMunicipio() {
        return this.delegacionMunicipio;
    }
    
    public void setDelegacionMunicipio(String delegacionMunicipio) {
        this.delegacionMunicipio = delegacionMunicipio;
    }
    public String getCiudad() {
        return this.ciudad;
    }
    
    public void setCiudad(String ciudad) {
        this.ciudad = ciudad;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public String getCodigoPostal() {
        return this.codigoPostal;
    }
    
    public void setCodigoPostal(String codigoPostal) {
        this.codigoPostal = codigoPostal;
    }
    public String getNombreScore() {
        return this.nombreScore;
    }
    
    public void setNombreScore(String nombreScore) {
        this.nombreScore = nombreScore;
    }
    public String getCodigoScore() {
        return this.codigoScore;
    }
    
    public void setCodigoScore(String codigoScore) {
        this.codigoScore = codigoScore;
    }
    public String getValorScore() {
        return this.valorScore;
    }
    
    public void setValorScore(String valorScore) {
        this.valorScore = valorScore;
    }
    public String getCuentas() {
        return this.cuentas;
    }
    
    public void setCuentas(String cuentas) {
        this.cuentas = cuentas;
    }
    public Date getFechaConsulta() {
        return this.fechaConsulta;
    }
    
    public void setFechaConsulta(Date fechaConsulta) {
        this.fechaConsulta = fechaConsulta;
    }




}


